name: deploy on npmjs.com

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: install dependencies
      run: npm install

    - name: build
      run: npm run build

    - name: test
      run: npm t

    - name: security
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > .npmrc

    - name: deploy npmjs.com
      run: npm publish --access public

