name: deploy on gcr.io 

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: release
        id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          release-type: node
          package-name: recursive-yaml-loader

      - name: setup repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with: 
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - name: install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: build
        run: yarn build

      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: yarn publish