name: NodeJS with Grunt

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: npm install

    - name: build
      run: npm run build

    - name: security
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > dist/.npmrc

    - name: cp package.json
      run: cp package*.json dist/

    - name: deploy
      run: |
        cd dist
        npm install --production
        npm version
        npm publish
